# permissions for end users to edit ldapusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ldapuser-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ldap-operator
    app.kubernetes.io/part-of: ldap-operator
    app.kubernetes.io/managed-by: kustomize
  name: ldapuser-editor-role
rules:
- apiGroups:
  - ldap.gopkg.blog
  resources:
  - ldapusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ldap.gopkg.blog
  resources:
  - ldapusers/status
  verbs:
  - get
