---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ldap.gopkg.blog
  resources:
  - ldapusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ldap.gopkg.blog
  resources:
  - ldapusers/finalizers
  verbs:
  - update
- apiGroups:
  - ldap.gopkg.blog
  resources:
  - ldapusers/status
  verbs:
  - get
  - patch
  - update
